version: "2"
services:
   rsync:
     image: shuosc/rsync:latest
     ports:
       - "873:873"
     volumes:
       - ./logs:/var/log/rsync
       - ./:/opt/rsync
       - /home/zhonger/ftp:/var/www/data
     restart: always
     privileged: true