version: "2"
services:
   apache:
     image: shuosc/apache2:latest
     ports:
       - "8090:80"
     volumes:
       - ./:/opt/apache2
       - /home/zhonger/ftp/:/var/www/data
     restart: always